### ISSUE TITLE
wasn't logging in correctly - user application id not user id

### ISSUE THREAD

**Issue by lao8n** [lao8n/cnstlltn#107]

**Comment by lao8n** [comment]
Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID
File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 754, in init_beanie
await Initializer(
File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 123, in __init__
self.document_models.sort(
File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/init.py", line 124, in <lambda>
key=lambda val: sort_order[val.get_model_type()]
AttributeError: 'list' object has no attribute 'get_model_type'

**Comment by lao8n** [comment]
2024-08-20T22:02:44.560521712Z INFO:     100.100.0.18:46480 - "GET /login-config HTTP/1.1" 200 OK
2024-08-20T22:02:47.170719883Z google user id:  105382063608919026910
2024-08-20T22:02:47.170764378Z userid:  <coroutine object get_or_create_user at 0x7580ec618cf0>
2024-08-20T22:02:47.170772442Z INFO:     100.100.0.108:56708 - "POST /login/google HTTP/1.1" 500 Internal Server Error
2024-08-20T22:02:47.171568637Z ERROR:    Exception in ASGI application
2024-08-20T22:02:47.171585344Z Traceback (most recent call last):
2024-08-20T22:02:47.171592309Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-08-20T22:02:47.171597331Z     result = await app(  # type: ignore[func-returns-value]
2024-08-20T22:02:47.171601919Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-20T22:02:47.171605885Z     return await self.app(scope, receive, send)
2024-08-20T22:02:47.171623536Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-08-20T22:02:47.171627930Z     await super().__call__(scope, receive, send)
2024-08-20T22:02:47.171631653Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-20T22:02:47.171635414Z     await self.middleware_stack(scope, receive, send)
2024-08-20T22:02:47.171639541Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-20T22:02:47.171643529Z     raise exc
2024-08-20T22:02:47.171647487Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-20T22:02:47.171651900Z     await self.app(scope, receive, _send)
2024-08-20T22:02:47.171656624Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-20T22:02:47.171660802Z     await self.app(scope, otel_receive, otel_send)
2024-08-20T22:02:47.171665370Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-20T22:02:47.171671123Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-20T22:02:47.171675437Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-20T22:02:47.171680369Z     await self.app(scope, receive, send)
2024-08-20T22:02:47.171684600Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-20T22:02:47.171689239Z     raise exc
2024-08-20T22:02:47.171693648Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-20T22:02:47.171697585Z     await self.app(scope, receive, sender)
2024-08-20T22:02:47.171701801Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-08-20T22:02:47.171706108Z     raise e
2024-08-20T22:02:47.171710095Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-08-20T22:02:47.171714299Z     await self.app(scope, receive, send)
2024-08-20T22:02:47.171718415Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-20T22:02:47.171722761Z     await route.handle(scope, receive, send)
2024-08-20T22:02:47.171726373Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-20T22:02:47.171730482Z     await self.app(scope, receive, send)
2024-08-20T22:02:47.171734603Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-20T22:02:47.171738729Z     response = await func(request)
2024-08-20T22:02:47.171759257Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 292, in app
2024-08-20T22:02:47.171765111Z     content = await serialize_response(
2024-08-20T22:02:47.171769495Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 155, in serialize_response
2024-08-20T22:02:47.171773611Z     raise ResponseValidationError(
2024-08-20T22:02:47.171777732Z fastapi.exceptions.ResponseValidationError: 1 validation errors:
2024-08-20T22:02:47.171782975Z   {'type': 'string_type', 'loc': ('response',), 'msg': 'Input should be a valid string', 'input': <coroutine object get_or_create_user at 0x7580ec618cf0>, 'url': 'https://errors.pydantic.dev/2.8/v/string_type'}
