### ISSUE TITLE
bit complicated to learn how to use

### ISSUE THREAD

**Issue by lao8n** [lao8n/cnstlltn#117]
yeah i guess you need to add a 1. add a constellation 2. prompt for some notes 3. save the ones you want 4. clusterby -> a bit complicated..
maybe add a playground constellation...

**Comment by lao8n** [comment]
add a tutorial constellation

**Comment by lao8n** [comment]
2024-08-21T23:23:01.290768517Z get_cluster_by_options params: 9b4ada25-b6a9-4652-a500-f2a5e2b88ea5 Home
2024-08-21T23:23:01.290802685Z getting constellation
2024-08-21T23:23:01.290809284Z get_cluster_by_options returns: []
2024-08-21T23:23:01.290814461Z INFO:     100.100.0.76:58558 - "GET /get-cluster-by-options?constellationName=Home HTTP/1.1" 200 OK
2024-08-21T23:23:01.694239059Z INFO:     100.100.0.76:58568 - "GET /get-constellation?constellationName=Home HTTP/1.1" 200 OK
2024-08-21T23:23:02.014208628Z get_clusters params: 9b4ada25-b6a9-4652-a500-f2a5e2b88ea5 Home  true
2024-08-21T23:23:02.014243695Z get_clusters returns: []

**Comment by lao8n** [comment]
9b4ada25-b6a9-4652-a500-f2a5e2b88ea5
mine
{
	"_id" : ObjectId("66c5143564b2b1beb286eab8"),
	"userid" : "36682b65-892a-4169-9281-faf6ab5687e2",
	"googleid" : "105382063608919026910"
}
haleemas
{
	"_id" : ObjectId("66c5158364b2b1beb286eab9"),
	"userid" : "90f8bf91-f076-4932-ba6d-4329d2aac24c",
	"googleid" : "115975342899738469340"
}
links
{
	"_id" : ObjectId("66c65dc29978167178f5ddcf"),
	"userid" : "20991a38-c2aa-448c-a36c-dfe46b209860",
	"googleid" : "110353484214596415873"
}

**Comment by lao8n** [comment]
l Server Error
2024-08-21T23:50:51.023143079Z ERROR:    Exception in ASGI application
2024-08-21T23:50:51.023165191Z Traceback (most recent call last):
2024-08-21T23:50:51.023170567Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-08-21T23:50:51.023175035Z     result = await app(  # type: ignore[func-returns-value]
2024-08-21T23:50:51.023179091Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-21T23:50:51.023183420Z     return await self.app(scope, receive, send)
2024-08-21T23:50:51.023187326Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-08-21T23:50:51.023191092Z     await super().__call__(scope, receive, send)
2024-08-21T23:50:51.023200455Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-21T23:50:51.023204684Z     await self.middleware_stack(scope, receive, send)
2024-08-21T23:50:51.023208339Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-21T23:50:51.023212380Z     raise exc
2024-08-21T23:50:51.023216090Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-21T23:50:51.023219839Z     await self.app(scope, receive, _send)
2024-08-21T23:50:51.023234218Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-21T23:50:51.023238123Z     await self.app(scope, otel_receive, otel_send)
2024-08-21T23:50:51.023242043Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-21T23:50:51.023246114Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-21T23:50:51.023249984Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-21T23:50:51.023253666Z     await self.app(scope, receive, send)
2024-08-21T23:50:51.023257473Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-21T23:50:51.023261377Z     raise exc
2024-08-21T23:50:51.023265211Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-21T23:50:51.023268806Z     await self.app(scope, receive, sender)
2024-08-21T23:50:51.023272430Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-08-21T23:50:51.023276142Z     raise e
2024-08-21T23:50:51.023279795Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-08-21T23:50:51.023283708Z     await self.app(scope, receive, send)
2024-08-21T23:50:51.023287265Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-21T23:50:51.023291468Z     await route.handle(scope, receive, send)
2024-08-21T23:50:51.023295836Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-21T23:50:51.023299575Z     await self.app(scope, receive, send)
2024-08-21T23:50:51.023303178Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-21T23:50:51.023306817Z     response = await func(request)
2024-08-21T23:50:51.023310863Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-08-21T23:50:51.023321317Z     raw_response = await run_endpoint_function(
2024-08-21T23:50:51.023326103Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-21T23:50:51.023330726Z     return await dependant.call(**values)
2024-08-21T23:50:51.023334484Z   File "/code/todo/login.py", line 19, in google_login
2024-08-21T23:50:51.023338138Z     userid = await get_or_create_user(str(google_user_id))
2024-08-21T23:50:51.023341900Z   File "/code/todo/login.py", line 38, in get_or_create_user
2024-08-21T23:50:51.023345572Z     saved_user_framework = await UserFramework.find(
2024-08-21T23:50:51.023349201Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/queries/find.py", line 679, in first_or_none
2024-08-21T23:50:51.023354334Z     res = await self.limit(1).to_list()
2024-08-21T23:50:51.023358070Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/queries/cursor.py", line 72, in to_list
2024-08-21T23:50:51.023361903Z     cursor = self.motor_cursor
2024-08-21T23:50:51.023365584Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/queries/find.py", line 665, in motor_cursor
2024-08-21T23:50:51.023368933Z     return self.document_model.get_motor_collection().find(
2024-08-21T23:50:51.023389856Z   File "/usr/local/lib/python3.10/site-packages/motor/core.py", line 1000, in find
2024-08-21T23:50:51.023394515Z     cursor = self.delegate.find(*unwrap_args_session(args), **unwrap_kwargs_session(kwargs))
2024-08-21T23:50:51.023398305Z   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 1685, in find
2024-08-21T23:50:51.023408846Z     return Cursor(self, *args, **kwargs)
2024-08-21T23:50:51.023412897Z TypeError: Cursor.__init__() got an unexpected keyword argument 'userid

**Comment by lao8n** [comment]
2024-08-22T00:35:05.856511977Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-08-22T00:35:05.856515950Z     result = await app(  # type: ignore[func-returns-value]
2024-08-22T00:35:05.856519058Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-22T00:35:05.856522048Z     return await self.app(scope, receive, send)
2024-08-22T00:35:05.856525243Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-08-22T00:35:05.856528304Z     await super().__call__(scope, receive, send)
2024-08-22T00:35:05.856531316Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-22T00:35:05.856534472Z     await self.middleware_stack(scope, receive, send)
2024-08-22T00:35:05.856538767Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-22T00:35:05.856543241Z     raise exc
2024-08-22T00:35:05.856547260Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-22T00:35:05.856550841Z     await self.app(scope, receive, _send)
2024-08-22T00:35:05.856555080Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-22T00:35:05.856558772Z     await self.app(scope, otel_receive, otel_send)
2024-08-22T00:35:05.856562746Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-22T00:35:05.856566957Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-22T00:35:05.856571219Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-22T00:35:05.856575767Z     await self.app(scope, receive, send)
2024-08-22T00:35:05.856579981Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-22T00:35:05.856584001Z     raise exc
2024-08-22T00:35:05.856588226Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-22T00:35:05.856592465Z     await self.app(scope, receive, sender)
2024-08-22T00:35:05.856597282Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-08-22T00:35:05.856601908Z     raise e
2024-08-22T00:35:05.856606535Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-08-22T00:35:05.856611456Z     await self.app(scope, receive, send)
2024-08-22T00:35:05.856616997Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-22T00:35:05.856621158Z     await route.handle(scope, receive, send)
2024-08-22T00:35:05.856625650Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-22T00:35:05.856629992Z     await self.app(scope, receive, send)
2024-08-22T00:35:05.856634658Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-22T00:35:05.856639155Z     response = await func(request)
2024-08-22T00:35:05.856643457Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-08-22T00:35:05.856647986Z     raw_response = await run_endpoint_function(
2024-08-22T00:35:05.856652218Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-22T00:35:05.856664958Z     return await dependant.call(**values)
2024-08-22T00:35:05.856669100Z   File "/code/todo/login.py", line 19, in google_login
2024-08-22T00:35:05.856673206Z     userid = await get_or_create_user(str(google_user_id))
2024-08-22T00:35:05.856677274Z   File "/code/todo/login.py", line 57, in get_or_create_user
2024-08-22T00:35:05.856681656Z     await user_cluster.save()
2024-08-22T00:35:05.856685926Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/actions.py", line 219, in wrapper
2024-08-22T00:35:05.856690323Z     result = await f(self, *args, skip_actions=skip_actions, **kwargs)
2024-08-22T00:35:05.856694562Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/state.py", line 66, in wrapper
2024-08-22T00:35:05.856698892Z     result = await f(self, *args, **kwargs)
2024-08-22T00:35:05.856703103Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/self_validation.py", line 12, in wrapper
2024-08-22T00:35:05.856707222Z     return await f(self, *args, **kwargs)
2024-08-22T00:35:05.856711582Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/documents.py", line 542, in save
2024-08-22T00:35:05.856715980Z     return await self.update(
2024-08-22T00:35:05.856720223Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/actions.py", line 219, in wrapper
2024-08-22T00:35:05.856724594Z     result = await f(self, *args, skip_actions=skip_actions, **kwargs)
2024-08-22T00:35:05.856729220Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/utils/state.py", line 66, in wrapper
2024-08-22T00:35:05.856733455Z     result = await f(self, *args, **kwargs)
2024-08-22T00:35:05.856737883Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/documents.py", line 658, in update
2024-08-22T00:35:05.856742469Z     result = await self.find_one(find_query).update(
2024-08-22T00:35:05.856747278Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/queries/update.py", line 351, in __await__
2024-08-22T00:35:05.856752030Z     update_result = yield from self._update().__await__()
2024-08-22T00:35:05.856767325Z   File "/usr/local/lib/python3.10/site-packages/beanie/odm/queries/update.py", line 319, in _update
2024-08-22T00:35:05.856772477Z     result = await self.document_model.get_motor_collection().find_one_and_update(
2024-08-22T00:35:05.856776909Z   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-08-22T00:35:05.856781336Z     result = self.fn(*self.args, **self.kwargs)
2024-08-22T00:35:05.856785993Z   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 3449, in find_one_and_update
2024-08-22T00:35:05.856790648Z     return self.__find_and_modify(
2024-08-22T00:35:05.856795003Z   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 3110, in __find_and_modify
2024-08-22T00:35:05.856799118Z     return self.__database.client._retryable_write(
2024-08-22T00:35:05.856803530Z   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1575, in _retryable_write
2024-08-22T00:35:05.856808008Z     return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
2024-08-22T00:35:05.856812526Z   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1461, in _retry_with_session
2024-08-22T00:35:05.856816920Z     return self._retry_internal(
2024-08-22T00:35:05.856821272Z   File "/usr/local/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
2024-08-22T00:35:05.856825834Z     return func(self, *args, **kwargs)
2024-08-22T00:35:05.856830496Z   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1507, in _retry_internal
2024-08-22T00:35:05.856845969Z     ).run()
2024-08-22T00:35:05.856851034Z   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 2353, in run
2024-08-22T00:35:05.856855525Z     return self._read() if self._is_read else self._write()
2024-08-22T00:35:05.856860046Z   File "/usr/local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 2470, in _write
2024-08-22T00:35:05.856863864Z     return self._func(self._session, conn, self._retryable)  # type: ignore
2024-08-22T00:35:05.856867639Z   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 3096, in _find_and_modify
2024-08-22T00:35:05.856871454Z     out = self._command(
2024-08-22T00:35:05.856875226Z   File "/usr/local/lib/python3.10/site-packages/pymongo/collection.py", line 301, in _command
2024-08-22T00:35:05.856879136Z     return conn.command(
2024-08-22T00:35:05.856882763Z   File "/usr/local/lib/python3.10/site-packages/pymongo/helpers.py", line 342, in inner
2024-08-22T00:35:05.856886278Z     return func(*args, **kwargs)
2024-08-22T00:35:05.856889788Z   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 1017, in command
2024-08-22T00:35:05.856893407Z     self._raise_connection_failure(error)
2024-08-22T00:35:05.856896821Z   File "/usr/local/lib/python3.10/site-packages/pymongo/pool.py", line 989, in command
2024-08-22T00:35:05.856900505Z     return command(
2024-08-22T00:35:05.856904384Z   File "/usr/local/lib/python3.10/site-packages/pymongo/network.py", line 152, in command
2024-08-22T00:35:05.856908044Z     request_id, msg, size, max_doc_size = message._op_msg(
2024-08-22T00:35:05.856911651Z   File "/usr/local/lib/python3.10/site-packages/pymongo/message.py", line 758, in _op_msg
2024-08-22T00:35:05.856915546Z     return _op_msg_uncompressed(flags, command, identifier, docs, opts)
2024-08-22T00:35:05.856919201Z bson.errors.InvalidDocument: documents must have only string keys, key was ObjectId('66c687b9b59f10a4e5fe9184')

**Comment by lao8n** [comment]
![Image](https://github.com/user-attachments/assets/ecd33c31-abef-41c8-a984-3c1f823dc1ca)
![Image](https://github.com/user-attachments/assets/29d48ab7-ff4e-4b7e-abb1-e890f886f89a)
