### ISSUE TITLE
have ai suggest how to cluster

### ISSUE THREAD

**Issue by lao8n** [lao8n/cnstlltn#58]

**Comment by lao8n** [comment]
024-08-04T19:37:14.421199562Z INFO:     100.100.0.80:59096 - "GET /get-cluster-suggestion?constellationName=Startup+Advice HTTP/1.1" 500 Internal Server Error
2024-08-04T19:37:14.421856673Z ERROR:    Exception in ASGI application
2024-08-04T19:37:14.421878765Z Traceback (most recent call last):
2024-08-04T19:37:14.421937457Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py", line 563, in use_span
2024-08-04T19:37:14.421950563Z     yield span
2024-08-04T19:37:14.421956428Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-04T19:37:14.421961509Z     await self.app(scope, otel_receive, otel_send)
2024-08-04T19:37:14.421966466Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-04T19:37:14.421971426Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-04T19:37:14.421990988Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-04T19:37:14.421996977Z     await self.app(scope, receive, send)
2024-08-04T19:37:14.422001667Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-04T19:37:14.422005652Z     raise exc
2024-08-04T19:37:14.422009717Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-04T19:37:14.422013697Z     await self.app(scope, receive, sender)
2024-08-04T19:37:14.422017576Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-08-04T19:37:14.422021528Z     raise e
2024-08-04T19:37:14.422025272Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-08-04T19:37:14.422029262Z     await self.app(scope, receive, send)
2024-08-04T19:37:14.422033558Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-04T19:37:14.422066206Z     await route.handle(scope, receive, send)
2024-08-04T19:37:14.422071092Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-04T19:37:14.422075216Z     await self.app(scope, receive, send)
2024-08-04T19:37:14.422079394Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-04T19:37:14.422083529Z     response = await func(request)
2024-08-04T19:37:14.422087419Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 255, in app
2024-08-04T19:37:14.422091431Z     content = await serialize_response(
2024-08-04T19:37:14.422095053Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 141, in serialize_response
2024-08-04T19:37:14.422098896Z     raise ValidationError(errors, field.type_)
2024-08-04T19:37:14.422102934Z pydantic.error_wrappers.ValidationError: <exception str() failed>
2024-08-04T19:37:14.422106689Z 
2024-08-04T19:37:14.422110684Z During handling of the above exception, another exception occurred:
2024-08-04T19:37:14.422114489Z 
2024-08-04T19:37:14.422118643Z Traceback (most recent call last):
2024-08-04T19:37:14.422122544Z   File "pydantic/error_wrappers.py", line 61, in pydantic.error_wrappers.ValidationError.errors
2024-08-04T19:37:14.422126302Z AttributeError: type object 'str' has no attribute '__config__'
2024-08-04T19:37:14.422129898Z 
2024-08-04T19:37:14.422143803Z During handling of the above exception, another exception occurred:
2024-08-04T19:37:14.422148047Z 
2024-08-04T19:37:14.422151919Z Traceback (most recent call last):
2024-08-04T19:37:14.422155782Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
2024-08-04T19:37:14.422159476Z     result = await app(  # type: ignore[func-returns-value]
2024-08-04T19:37:14.422163296Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-08-04T19:37:14.422167142Z     return await self.app(scope, receive, send)
2024-08-04T19:37:14.422171104Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2024-08-04T19:37:14.422175169Z     await super().__call__(scope, receive, send)
2024-08-04T19:37:14.422179076Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-04T19:37:14.422183227Z     await self.middleware_stack(scope, receive, send)
2024-08-04T19:37:14.422186937Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-04T19:37:14.422190501Z     raise exc
2024-08-04T19:37:14.422194512Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-04T19:37:14.422198589Z     await self.app(scope, receive, _send)
2024-08-04T19:37:14.422202396Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 431, in __call__
2024-08-04T19:37:14.422205914Z     with trace.use_span(span, end_on_exit=True) as current_span:
2024-08-04T19:37:14.422209827Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-08-04T19:37:14.422223889Z     self.gen.throw(typ, value, traceback)
2024-08-04T19:37:14.422228260Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py", line 571, in use_span
2024-08-04T19:37:14.422232595Z     span.record_exception(exc)
2024-08-04T19:37:14.422236620Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 944, in record_exception
2024-08-04T19:37:14.422240494Z     "exception.message": str(exception),
2024-08-04T19:37:14.422248499Z   File "pydantic/error_wrappers.py", line 71, in pydantic.error_wrappers.ValidationError.__str__
2024-08-04T19:37:14.422252606Z   File "pydantic/error_wrappers.py", line 63, in pydantic.error_wrappers.ValidationError.errors
2024-08-04T19:37:14.422256528Z AttributeError: type object 'str' has no attribute '__pydantic_model__'

**Comment by lao8n** [comment]
04T22:05:04.742693401Z suggest cluster response ChatCompletion(id='chatcmpl-9sddYfu0qazcCxGyYD4x0B5syUIH8', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='entrepreneurship, leadership, hiring practices, company culture, decision-making, startup strategies, customer service, education, technology skills, market focus', role='assistant', function_call=None, tool_calls=None))], created=1722809104, model='gpt-4o-mini-2024-07-18', object='chat.completion', service_tier=None, system_fingerprint='fp_611b667b19', usage=CompletionUsage(completion_tokens=28, prompt_tokens=1038, total_tokens=1066))
2024-08-04T22:05:04.742754005Z INFO:     100.100.0.80:53522 - "GET /get-cluster-suggestion?constellationName=Startup+Advice HTTP/1.1" 500 Internal Server Error
2024-08-04T22:05:04.743723033Z ERROR:    Exception in ASGI application
2024-08-04T22:05:04.743740724Z Traceback (most recent call last):
2024-08-04T22:05:04.743748301Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py", line 563, in use_span
2024-08-04T22:05:04.743753745Z     yield span
2024-08-04T22:05:04.743759759Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-04T22:05:04.743764353Z     await self.app(scope, otel_receive, otel_send)
2024-08-04T22:05:04.743769047Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-04T22:05:04.743774310Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-04T22:05:04.743779680Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-04T22:05:04.743784568Z     await self.app(scope, receive, send)
2024-08-04T22:05:04.743789701Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-04T22:05:04.743794702Z     raise exc
2024-08-04T22:05:04.743799645Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-04T22:05:04.743804847Z     await self.app(scope, receive, sender)
2024-08-04T22:05:04.743809830Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024-08-04T22:05:04.743814776Z     raise e
2024-08-04T22:05:04.743819313Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024-08-04T22:05:04.743823776Z     await self.app(scope, receive, send)
2024-08-04T22:05:04.743828529Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-04T22:05:04.743832904Z     await route.handle(scope, receive, send)
2024-08-04T22:05:04.743837244Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-04T22:05:04.743841615Z     await self.app(scope, receive, send)
2024-08-04T22:05:04.743845961Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-04T22:05:04.743850549Z     response = await func(request)
2024-08-04T22:05:04.743872250Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 255, in app
2024-08-04T22:05:04.743877287Z     content = await serialize_response(
2024-08-04T22:05:04.743882360Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 141, in serialize_response
2024-08-04T22:05:04.743887511Z     raise ValidationError(errors, field.type_)
2024-08-04T22:05:04.743892274Z pydantic.error_wrappers.ValidationError: <exception str() failed>
2024-08-04T22:05:04.743896639Z 
2024-08-04T22:05:04.743901791Z During handling of the above exception, another exception occurred:
2024-08-04T22:05:04.743906763Z 
2024-08-04T22:05:04.743910565Z Traceback (most recent call last):
2024-08-04T22:05:04.743914416Z   File "pydantic/error_wrappers.py", line 61, in pydantic.error_wrappers.ValidationError.errors
2024-08-04T22:05:04.743918260Z AttributeError: type object 'str' has no attribute '__config__'
2024-08-04T22:05:04.743922175Z 
2024-08-04T22:05:04.743926462Z During handling of the above exception, another exception occurred:
2024-08-04T22:05:04.743929948Z 
2024-08-04T22:05:04.743933917Z Traceback (most recent call last):
2024-08-04T22:05:04.743938141Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
2024-08-04T22:05:04.743942103Z     result = await app(  # type: ignore[func-returns-value]
2024-08-04T22:05:04.743945863Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024-08-04T22:05:04.743949850Z     return await self.app(scope, receive, send)
2024-08-04T22:05:04.743953980Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
2024-08-04T22:05:04.743958200Z     await super().__call__(scope, receive, send)
2024-08-04T22:05:04.743961965Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-04T22:05:04.743965548Z     await self.middleware_stack(scope, receive, send)
2024-08-04T22:05:04.743969255Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-04T22:05:04.743972890Z     raise exc
2024-08-04T22:05:04.743976573Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-04T22:05:04.743990855Z     await self.app(scope, receive, _send)
2024-08-04T22:05:04.743995503Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 431, in __call__
2024-08-04T22:05:04.743999453Z     with trace.use_span(span, end_on_exit=True) as current_span:
2024-08-04T22:05:04.744003349Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-08-04T22:05:04.744007096Z     self.gen.throw(typ, value, traceback)
2024-08-04T22:05:04.744010730Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py", line 571, in use_span
2024-08-04T22:05:04.744014842Z     span.record_exception(exc)
2024-08-04T22:05:04.744019341Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 944, in record_exception
2024-08-04T22:05:04.744023384Z     "exception.message": str(exception),
2024-08-04T22:05:04.744034383Z   File "pydantic/error_wrappers.py", line 71, in pydantic.error_wrappers.ValidationError.__str__
2024-08-04T22:05:04.744038788Z   File "pydantic/error_wrappers.py", line 63, in pydantic.error_wrappers.ValidationError.errors
2024-08-04T22:05:04.744042942Z AttributeError: type object 'str' has no attribute '__pydantic_model__'

**Comment by lao8n** [comment]
need to mkae clusterby update form - but also have clusterby be associated with each constellation..
