### ISSUE TITLE
completely remodel how clustering works

### ISSUE THREAD

**Issue by lao8n** [lao8n/cnstlltn#60]
we want clustering to support the following functions
1. cluster on demand both all elements and marginal element
2. get latest cluster and list of clusters available but have specific save cluster button
3. ai suggested clustering
4. be able to have more sophisticated clustering techniques.

apis
```
get-cluster(userId, constellationName, clusterby) -> List[Cluster] # could just be latest, this will return what clusterby actually is
get-cluster-suggestion(userId, constellationName) -> clusterby
get-cluster-by-options(userId, constellationName) -> List[str]
cluster-by(userId, constellationName, clusterby, clusterAll) -> UserFramework coords updated & cluster added
save-cluster(userId, constellationName, clusterby)
```

proposed internal model
```
class UserFramework(Document):
    userid: str # partition key
    constellation: str
    title: str
    content: str
    clusterby: Dict[str, Cluster] = Field(default_factory=dict) 
```
where clusterby latest will represent current data. 

clusters will be stored as 
```
class UserCluster(Document):
    userid: str
    constellation: str
    latest: bool
    clusterby: str
    cluster: str
    coordinate: Tuple[float, float]
```

**Comment by lao8n** [comment]
wasn't correctly abstracting dispatch - should put all that in actions

**Comment by lao8n** [comment]
managed to get the deployment to work and no errors and now login works - just working my way through the bugs the first one is 
```
8-10T22:17:28.752853003Z ERROR:    Exception in ASGI application
2024-08-10T22:17:28.752872478Z Traceback (most recent call last):
2024-08-10T22:17:28.752878673Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-08-10T22:17:28.752884714Z     result = await app(  # type: ignore[func-returns-value]
2024-08-10T22:17:28.752890242Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-10T22:17:28.752895687Z     return await self.app(scope, receive, send)
2024-08-10T22:17:28.752901383Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-08-10T22:17:28.752906632Z     await super().__call__(scope, receive, send)
2024-08-10T22:17:28.752911509Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-10T22:17:28.752916202Z     await self.middleware_stack(scope, receive, send)
2024-08-10T22:17:28.752920632Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-10T22:17:28.752925229Z     raise exc
2024-08-10T22:17:28.752929920Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-10T22:17:28.752934389Z     await self.app(scope, receive, _send)
2024-08-10T22:17:28.752939365Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-10T22:17:28.752944097Z     await self.app(scope, otel_receive, otel_send)
2024-08-10T22:17:28.752948619Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-10T22:17:28.752953199Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-10T22:17:28.752957839Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-10T22:17:28.752962715Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.752967599Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-10T22:17:28.752972400Z     raise exc
2024-08-10T22:17:28.752988251Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-10T22:17:28.752993643Z     await self.app(scope, receive, sender)
2024-08-10T22:17:28.752998623Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-08-10T22:17:28.753003897Z     raise e
2024-08-10T22:17:28.753009092Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-08-10T22:17:28.753067537Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.753073595Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-10T22:17:28.753092077Z     await route.handle(scope, receive, send)
2024-08-10T22:17:28.753097661Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-10T22:17:28.753103211Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.753107748Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-10T22:17:28.753112477Z     response = await func(request)
2024-08-10T22:17:28.753131605Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-08-10T22:17:28.753135580Z     raw_response = await run_endpoint_function(
2024-08-10T22:17:28.753139284Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-10T22:17:28.753143278Z     return await dependant.call(**values)
2024-08-10T22:17:28.753157671Z   File "/code/todo/routes.py", line 84, in get_constellation
2024-08-10T22:17:28.753172476Z     UserFramework.userid == user_id,
2024-08-10T22:17:28.753177637Z   File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 237, in __getattr__
2024-08-10T22:17:28.753183010Z     raise AttributeError(item)
2024-08-10T22:17:28.753187580Z AttributeError: userid
2024-08-10T22:17:28.784635515Z get_clusters params: 194094976957-s4uccitb516kkvcra1brbbe40398i6rl.apps.googleusercontent.com Home political, economic, sociological, technological, legal, environmental, psychological etc. None
2024-08-10T22:17:28.784659213Z INFO:     100.100.0.82:52780 - "GET /get-clusters?constellationName=Home&clusterBy=political,+economic,+sociological,+technological,+legal,+environmental,+psychological+etc. HTTP/1.1" 500 Internal Server Error
2024-08-10T22:17:28.785199035Z ERROR:    Exception in ASGI application
2024-08-10T22:17:28.785216216Z Traceback (most recent call last):
2024-08-10T22:17:28.785222405Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-08-10T22:17:28.785229911Z     result = await app(  # type: ignore[func-returns-value]
2024-08-10T22:17:28.785234756Z   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-10T22:17:28.785239541Z     return await self.app(scope, receive, send)
2024-08-10T22:17:28.785244326Z   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
2024-08-10T22:17:28.785255458Z     await super().__call__(scope, receive, send)
2024-08-10T22:17:28.785267329Z   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2024-08-10T22:17:28.785272268Z     await self.middleware_stack(scope, receive, send)
2024-08-10T22:17:28.785277496Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024-08-10T22:17:28.785282623Z     raise exc
2024-08-10T22:17:28.785287629Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024-08-10T22:17:28.785293010Z     await self.app(scope, receive, _send)
2024-08-10T22:17:28.785298043Z   File "/usr/local/lib/python3.10/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 459, in __call__
2024-08-10T22:17:28.785302607Z     await self.app(scope, otel_receive, otel_send)
2024-08-10T22:17:28.785307426Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-10T22:17:28.785329404Z     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-10T22:17:28.785334425Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-10T22:17:28.785339130Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.785344261Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-08-10T22:17:28.785349218Z     raise exc
2024-08-10T22:17:28.785354065Z   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-08-10T22:17:28.785358750Z     await self.app(scope, receive, sender)
2024-08-10T22:17:28.785363293Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-08-10T22:17:28.785367923Z     raise e
2024-08-10T22:17:28.785372958Z   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-08-10T22:17:28.785377641Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.785383723Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2024-08-10T22:17:28.785388393Z     await route.handle(scope, receive, send)
2024-08-10T22:17:28.785393353Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2024-08-10T22:17:28.785397978Z     await self.app(scope, receive, send)
2024-08-10T22:17:28.785402319Z   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2024-08-10T22:17:28.785407227Z     response = await func(request)
2024-08-10T22:17:28.785412475Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
2024-08-10T22:17:28.785417925Z     raw_response = await run_endpoint_function(
2024-08-10T22:17:28.785422739Z   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-10T22:17:28.785427636Z     return await dependant.call(**values)
2024-08-10T22:17:28.785432630Z   File "/code/todo/routes.py", line 95, in get_clusters
2024-08-10T22:17:28.785437707Z     user_clusters = await cl.get_clusters(user_id, constellation_name, cluster_by, latest)
2024-08-10T22:17:28.785442682Z   File "/code/todo/cluster.py", line 23, in get_clusters
2024-08-10T22:17:28.785447759Z     UserCluster.userid == user_id,
2024-08-10T22:17:28.785452945Z   File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 237, in __getattr__
2024-08-10T22:17:28.785457826Z     raise AttributeError(item)
2024-08-10T22:17:28.785463485Z AttributeError: userid
```

**Comment by lao8n** [comment]
so we do have some data
{
	"_id" : ObjectId("66b9043934c40d13fc4a0ea2"),
	"userid" : "194094976957-s4uccitb516kkvcra1brbbe40398i6rl.apps.googleusercontent.com",
	"constellation" : "Home",
	"clusterby" : "political, economic, sociological, technological, legal, environmental, psychological etc.",
	"cluster" : "Legal",
	"islatest" : true,
	"coordinate" : [
		0.2784107345127083,
		0.796828731832767
	],
	"frameworks" : {
		"66a81c605c5b9d3e10dad79b" : [
			0.37635282443574514,
			0.8667815752420077
		],
		"66a821585459ba5063e3b8c5" : [
			0.30357820933434576,
			0.7289300248909657
		],
		"66aa49e952d8818a5da736ef" : [
			0.1566826984245347,
			0.6877192676557338
		]
	}
}

**Comment by lao8n** [comment]
basically works now.. might be a few specific bugs...
